name: Build Makefile

on: 
  workflow_dispatch:

jobs:
  build_using_makefile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install Dependencies
        run: npm install
        
      - name: Run index.js
        run: make run
